/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicegeneratingsystem;

/**
 *
 * @author user
 */
public class Calculator extends javax.swing.JFrame {

        double firstNum;
        double secondNum;
        double result;
        String sign;
        
    /**
     * Creates new form GridPanel
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GridLayout = new javax.swing.JPanel();
        buttonmodulus = new javax.swing.JButton();
        buttondivision = new javax.swing.JButton();
        buttonmultiplication = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        buttonequals = new javax.swing.JButton();
        buttonplus = new javax.swing.JButton();
        buttonminus = new javax.swing.JButton();
        buttonplusminus = new javax.swing.JButton();
        buttonC = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        button0 = new javax.swing.JButton();
        buttondot = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setResizable(false);

        GridLayout.setLayout(new java.awt.GridLayout(4, 4, 1, 3));

        buttonmodulus.setBackground(new java.awt.Color(153, 153, 153));
        buttonmodulus.setForeground(new java.awt.Color(51, 0, 0));
        buttonmodulus.setText("%");
        buttonmodulus.setBorder(new javax.swing.border.MatteBorder(null));
        GridLayout.add(buttonmodulus);

        buttondivision.setBackground(new java.awt.Color(153, 153, 153));
        buttondivision.setForeground(new java.awt.Color(51, 0, 0));
        buttondivision.setText("/");
        buttondivision.setBorder(new javax.swing.border.MatteBorder(null));
        buttondivision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondivisionActionPerformed(evt);
            }
        });
        GridLayout.add(buttondivision);

        buttonmultiplication.setBackground(new java.awt.Color(153, 153, 153));
        buttonmultiplication.setForeground(new java.awt.Color(51, 0, 0));
        buttonmultiplication.setText("*");
        buttonmultiplication.setBorder(new javax.swing.border.MatteBorder(null));
        buttonmultiplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonmultiplicationActionPerformed(evt);
            }
        });
        GridLayout.add(buttonmultiplication);

        button9.setBackground(new java.awt.Color(0, 0, 255));
        button9.setForeground(new java.awt.Color(204, 204, 204));
        button9.setText("9");
        button9.setBorder(new javax.swing.border.MatteBorder(null));
        button9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button9ActionPerformed(evt);
            }
        });
        GridLayout.add(button9);

        button8.setBackground(new java.awt.Color(0, 0, 255));
        button8.setForeground(new java.awt.Color(204, 204, 204));
        button8.setText("8");
        button8.setToolTipText("");
        button8.setBorder(new javax.swing.border.MatteBorder(null));
        button8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button8ActionPerformed(evt);
            }
        });
        GridLayout.add(button8);

        button7.setBackground(new java.awt.Color(0, 0, 255));
        button7.setForeground(new java.awt.Color(204, 204, 204));
        button7.setText("7");
        button7.setBorder(new javax.swing.border.MatteBorder(null));
        button7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button7ActionPerformed(evt);
            }
        });
        GridLayout.add(button7);

        button6.setBackground(new java.awt.Color(0, 0, 255));
        button6.setForeground(new java.awt.Color(204, 204, 204));
        button6.setText("6");
        button6.setBorder(new javax.swing.border.MatteBorder(null));
        button6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button6ActionPerformed(evt);
            }
        });
        GridLayout.add(button6);

        button5.setBackground(new java.awt.Color(0, 0, 255));
        button5.setForeground(new java.awt.Color(204, 204, 204));
        button5.setText("5");
        button5.setBorder(new javax.swing.border.MatteBorder(null));
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        GridLayout.add(button5);

        button4.setBackground(new java.awt.Color(0, 0, 255));
        button4.setForeground(new java.awt.Color(204, 204, 204));
        button4.setText("4");
        button4.setBorder(new javax.swing.border.MatteBorder(null));
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        GridLayout.add(button4);

        button3.setBackground(new java.awt.Color(0, 0, 255));
        button3.setForeground(new java.awt.Color(204, 204, 204));
        button3.setText("3");
        button3.setBorder(new javax.swing.border.MatteBorder(null));
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        GridLayout.add(button3);

        button2.setBackground(new java.awt.Color(0, 0, 255));
        button2.setForeground(new java.awt.Color(204, 204, 204));
        button2.setText("2");
        button2.setBorder(new javax.swing.border.MatteBorder(null));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        GridLayout.add(button2);

        button1.setBackground(new java.awt.Color(0, 0, 255));
        button1.setForeground(new java.awt.Color(204, 204, 204));
        button1.setText("1");
        button1.setBorder(new javax.swing.border.MatteBorder(null));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        GridLayout.add(button1);

        jTextField1.setEditable(false);
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        buttonequals.setBackground(new java.awt.Color(153, 153, 153));
        buttonequals.setForeground(new java.awt.Color(51, 0, 0));
        buttonequals.setText("=");
        buttonequals.setBorder(new javax.swing.border.MatteBorder(null));
        buttonequals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonequalsActionPerformed(evt);
            }
        });

        buttonplus.setBackground(new java.awt.Color(153, 153, 153));
        buttonplus.setForeground(new java.awt.Color(51, 0, 0));
        buttonplus.setText("+");
        buttonplus.setBorder(new javax.swing.border.MatteBorder(null));
        buttonplus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonplusActionPerformed(evt);
            }
        });

        buttonminus.setBackground(new java.awt.Color(153, 153, 153));
        buttonminus.setForeground(new java.awt.Color(51, 0, 0));
        buttonminus.setText("-");
        buttonminus.setBorder(new javax.swing.border.MatteBorder(null));
        buttonminus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonminusActionPerformed(evt);
            }
        });

        buttonplusminus.setBackground(new java.awt.Color(153, 153, 153));
        buttonplusminus.setForeground(new java.awt.Color(51, 0, 0));
        buttonplusminus.setText("+/-");
        buttonplusminus.setBorder(new javax.swing.border.MatteBorder(null));

        buttonC.setBackground(new java.awt.Color(204, 0, 0));
        buttonC.setForeground(new java.awt.Color(51, 0, 0));
        buttonC.setText("C");
        buttonC.setBorder(new javax.swing.border.MatteBorder(null));
        buttonC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(buttonequals, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonplusminus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonplus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(buttonplus, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonminus, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonplusminus, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonC, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonequals, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        button0.setBackground(new java.awt.Color(0, 0, 255));
        button0.setForeground(new java.awt.Color(204, 204, 204));
        button0.setText("0");
        button0.setBorder(new javax.swing.border.MatteBorder(null));
        button0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button0ActionPerformed(evt);
            }
        });

        buttondot.setBackground(new java.awt.Color(153, 153, 153));
        buttondot.setForeground(new java.awt.Color(51, 0, 0));
        buttondot.setText(".");
        buttondot.setBorder(new javax.swing.border.MatteBorder(null));
        buttondot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttondotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(button0, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(button0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(buttondot, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GridLayout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GridLayout, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button8ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button8.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button8ActionPerformed

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button5.getText();
        jTextField1.setText(input);
        
    }//GEN-LAST:event_button5ActionPerformed

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button2.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button2ActionPerformed

    private void buttondivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondivisionActionPerformed
        // TODO add your handling code here:
         firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        sign = "/";
    }//GEN-LAST:event_buttondivisionActionPerformed

    private void button9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button9ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button9.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button9ActionPerformed

    private void button7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button7ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button7.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button7ActionPerformed

    private void button6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button6ActionPerformed
       // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button6.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button6ActionPerformed

    private void buttonequalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonequalsActionPerformed
        // TODO add your handling code here:
       String answer;
       secondNum = Double.parseDouble(jTextField1.getText());
        switch(sign){
            case "+": 
                result = firstNum + secondNum;
                answer = String.format("%.0f", result);
                jTextField1.setText(answer);
                break;
                
            case "-": 
                result = firstNum - secondNum;
                answer = String.format("%.0f", result);
                jTextField1.setText(answer);
                break;
             case "*": 
                result = firstNum * secondNum;
                answer = String.format("%.0f", result);
                jTextField1.setText(answer);
                break;    
                 
             case "/": 
                result = firstNum / secondNum;
                answer = String.format("%.0f", result);
                jTextField1.setText(answer);
                break;     
                
        }
        
    }//GEN-LAST:event_buttonequalsActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button1.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button1ActionPerformed

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button3.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button3ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button4.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button4ActionPerformed

    private void button0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button0ActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + button0.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_button0ActionPerformed

    private void buttondotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttondotActionPerformed
        // TODO add your handling code here:
        String input;
        input = jTextField1.getText() + buttondot.getText();
        jTextField1.setText(input);
    }//GEN-LAST:event_buttondotActionPerformed

    private void buttonCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCActionPerformed
        // TODO add your handling code here:
        jTextField1.setText(null);
    }//GEN-LAST:event_buttonCActionPerformed

    private void buttonplusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonplusActionPerformed
        // TODO add your handling code here:
        firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        sign = "+";
    }//GEN-LAST:event_buttonplusActionPerformed

    private void buttonminusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonminusActionPerformed
        // TODO add your handling code here:
         firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        sign = "-";
    }//GEN-LAST:event_buttonminusActionPerformed

    private void buttonmultiplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonmultiplicationActionPerformed
        // TODO add your handling code here:
         firstNum = Double.parseDouble(jTextField1.getText());
        jTextField1.setText(null);
        sign = "*";
    }//GEN-LAST:event_buttonmultiplicationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GridLayout;
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonC;
    private javax.swing.JButton buttondivision;
    private javax.swing.JButton buttondot;
    private javax.swing.JButton buttonequals;
    private javax.swing.JButton buttonminus;
    private javax.swing.JButton buttonmodulus;
    private javax.swing.JButton buttonmultiplication;
    private javax.swing.JButton buttonplus;
    private javax.swing.JButton buttonplusminus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
