/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package invoicegeneratingsystem.viewoptions;
import invoicegeneratingsystem.Welcome;
import invoicegeneratingsystem.dao.DaoPattern;
import invoicegeneratingsystem.dao.ReturnType;

/**
 *
 * @author user
 */
public class ViewOptions extends javax.swing.JFrame {

    /**
     * Creates new form ViewOptions
     */
    public ViewOptions() {
        initComponents();
        setTitle("View Options");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewCustomerInformationbtn = new javax.swing.JButton();
        viewInvoiceInformationbtn = new javax.swing.JButton();
        viewRentalInformationbtn = new javax.swing.JButton();
        viewCarInformationbtn = new javax.swing.JButton();
        viewTransactionInformationbtn = new javax.swing.JButton();
        viewCompiledInvoicebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        viewCustomerInformationbtn.setText("View Customer Information");
        viewCustomerInformationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerInformationbtnActionPerformed(evt);
            }
        });

        viewInvoiceInformationbtn.setText("View Invoice Information");
        viewInvoiceInformationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewInvoiceInformationbtnActionPerformed(evt);
            }
        });

        viewRentalInformationbtn.setText("View Rental Information");
        viewRentalInformationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRentalInformationbtnActionPerformed(evt);
            }
        });

        viewCarInformationbtn.setText("View Car Information");
        viewCarInformationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCarInformationbtnActionPerformed(evt);
            }
        });

        viewTransactionInformationbtn.setText("View Transaction Information");
        viewTransactionInformationbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTransactionInformationbtnActionPerformed(evt);
            }
        });

        viewCompiledInvoicebtn.setText("View Compiled Invoice");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCustomerInformationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewInvoiceInformationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewRentalInformationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCarInformationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewTransactionInformationbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewCompiledInvoicebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(123, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backbtn)
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewCustomerInformationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewInvoiceInformationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewRentalInformationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCarInformationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewTransactionInformationbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewCompiledInvoicebtn)
                .addGap(18, 18, 18)
                .addComponent(backbtn)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
           Welcome page = new Welcome();
                page.setVisible(true);
                 this.setVisible(false);
    }//GEN-LAST:event_backbtnActionPerformed

    private void viewCustomerInformationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerInformationbtnActionPerformed
        // TODO add your handling code here:
        ReturnType r = new DaoPattern().adminView("customer");
        ViewCustomerForm customer = new ViewCustomerForm();
        customer.setVisible(true);
        customer.setTable(r);
        this.setVisible(false);
        
    }//GEN-LAST:event_viewCustomerInformationbtnActionPerformed

    private void viewInvoiceInformationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewInvoiceInformationbtnActionPerformed
        // TODO add your handling code here:
        ReturnType r = new DaoPattern().adminView("invoice");
        ViewCustomerForm customer = new ViewCustomerForm();
        customer.setVisible(true);
        customer.setTable(r);
        this.setVisible(false);
    }//GEN-LAST:event_viewInvoiceInformationbtnActionPerformed

    private void viewTransactionInformationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTransactionInformationbtnActionPerformed
        // TODO add your handling code here:
        ReturnType r = new DaoPattern().adminView("transactions");
        ViewCustomerForm customer = new ViewCustomerForm();
        customer.setVisible(true);
        customer.setTable(r);
        this.setVisible(false);
    }//GEN-LAST:event_viewTransactionInformationbtnActionPerformed

    private void viewRentalInformationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRentalInformationbtnActionPerformed
        // TODO add your handling code here:
            ReturnType r = new DaoPattern().adminView("rentinformation");
        ViewCustomerForm customer = new ViewCustomerForm();
        customer.setVisible(true);
        customer.setTable(r);
        this.setVisible(false);
    }//GEN-LAST:event_viewRentalInformationbtnActionPerformed

    private void viewCarInformationbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCarInformationbtnActionPerformed
        // TODO add your handling code here:
        ReturnType r = new DaoPattern().adminView("car");
        ViewCustomerForm customer = new ViewCustomerForm();
        customer.setVisible(true);
        customer.setTable(r);
        this.setVisible(false);
    }//GEN-LAST:event_viewCarInformationbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton viewCarInformationbtn;
    private javax.swing.JButton viewCompiledInvoicebtn;
    private javax.swing.JButton viewCustomerInformationbtn;
    private javax.swing.JButton viewInvoiceInformationbtn;
    private javax.swing.JButton viewRentalInformationbtn;
    private javax.swing.JButton viewTransactionInformationbtn;
    // End of variables declaration//GEN-END:variables
}
